[View in Colaboratory](https://colab.research.google.com/github/yishnu96/Assignment-4/blob/yishnu96/First_Date_with_TensorFlow.ipynb)

# First Date with TensorFlow

Hi all,<br/>

You know what's important for understanding Deep Learning / Machine Learning?<br/>
Intuition. Period.

And Intuition comes when you run the code multiple times.

So, today I can write a couple of defination and say this is this, this is that.<br/>
You Google half of the things up. You find answers which you need to Google further.<br/>
In the process, you probably won't even remember what's the first thing you started out with!

So?

Hence on, I will execute cells with code. <br/>
The neurons in your brain will optimize a function to get a hold of what each function is doing.<br/>
**No Theory Just Code.**

I will at max give a defination that extends for a line. That's it.<br/>
Let's get started!

<hr/>

**RECOMMENDED!**<br/>
Write the code in the cells using the signals sent by your brain to your fingers!<br/>
Don't just `shift+enter` the cells.

[Source](https://github.com/iArunava/TensorFlow-NoteBooks)

In [0]:
# Essential imports
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [0]:
# Let's define some tensors
t1 = tf.constant(2.0, dtype=tf.float32)
t2 = tf.constant([1.0, 2.0], dtype=tf.float32)
t3 = tf.constant([[[1.0, 9.0], [2.0, 3.0], [4.0, 5.0]], 
                  [[1.0, 9.0], [2.0, 3.0], [4.0, 5.0]]])

In [4]:
# Let's print them out!
print (t1)
print (t2)
print (t3)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(2,), dtype=float32)
Tensor("Const_2:0", shape=(2, 3, 2), dtype=float32)


Where's Waldo?<br/>
I mean, the value?<br/>

So, the thing is you can't print the value of tensors directly.<br/>
You have to use `session`, so let's do that!

In [5]:
sess = tf.Session()
print (sess.run(t1))
print ("=======================")
print (sess.run(t2))
print ("=======================")
print (sess.run(t3))
sess.close()

2.0
[1. 2.]
[[[1. 9.]
  [2. 3.]
  [4. 5.]]

 [[1. 9.]
  [2. 3.]
  [4. 5.]]]


Aaahaa!! Just printed those tensors!!!<br/>
Feels good! <br/>

For some of you, who are like, dude you got "No Theory Just Code" in bold <br/>
And you are still using the markdown cells for the theory ?!

I am just gonna say I am a unreasonable man.<br/>


So, you are programming with tf.<br/>
What ever you do is broken down to 2 basic steps:
- Building the computational Graph!
- Execute that graph using `session`!

That's all!

<hr/>

Let's compare this 2 steps with what we did above!<br/>
So, I defined 3 `tensor`s and these 3 `tensor`s formed my computational Graph.<br/>
And then I executed each tensor in this graph using a `session`.

That simple!

<hr/>

Now, let's define a few more computational graphs and execute them with sessions.

Okay, to start with let's build this computational graph!

![Comp Graph 1](https://raw.githubusercontent.com/iArunava/TensorFlow-NoteBooks/master/assets/comp_graph_1.jpg)

In [6]:
# Let's define the graph
comp_graph_1 = tf.multiply(tf.add(78, 19), 79)

# Alternatively
comp_graph_1_alt = (tf.constant(78) + tf.constant(19)) * tf.constant(79)

# Let's execute using session
sess = tf.Session()
print ('Comp Graph 1    : ', sess.run(comp_graph_1))
print ('Comp Graph 1 Alt: ', sess.run(comp_graph_1_alt))
sess.close()

Comp Graph 1    :  7663
Comp Graph 1 Alt:  7663


Let's define a sligtly more involved graph!

![alt text](https://raw.githubusercontent.com/iArunava/TensorFlow-NoteBooks/master/assets/comp_graph_2.jpg)

In [7]:
# Let build the graph
# We need to cast cause the tensors operated on should be of the same type
comp_graph_part_1 = tf.cast(tf.subtract(tf.add(7, 8), tf.add(9, 10)), 
                            dtype=tf.float32)
comp_graph_part_2 = tf.divide(tf.cast(tf.multiply(7, 10), dtype=tf.float32), tf.constant(19.5))
comp_graph_complete = tf.maximum(comp_graph_part_1, comp_graph_part_2)

# Let's execute
sess = tf.Session()
part1_res, part2_res, total_res = sess.run([comp_graph_part_1, comp_graph_part_2, comp_graph_complete])
print ('Complete Result: ', total_res)
print ('Part 1 Result: ', part1_res)
print ('Part 2 Result: ', part2_res)
sess.close()

Complete Result:  3.5897436
Part 1 Result:  -4.0
Part 2 Result:  3.5897436


Cool! Let's go! Build another graph and execute it with sessions.<br/>

But this time, it's all you!

Build this graph and execute it with `session`!

![alt text](https://raw.githubusercontent.com/iArunava/TensorFlow-NoteBooks/master/assets/comp_graph_3.jpg)

_Remember that `tensors` operated on should be of the same type!_<br/>
_Search up errors and other help you need on Google_

In [9]:
# Build the graph
t1 = tf.constant([9.0, 10.0]) 
t2 = tf.constant([7.0, 8.65]) 
t3 = tf.constant([7.65, 9.0]) 
t4 = tf.constant([13.5, 7.18]) 
                  

graph_1 = t1 * t2
graph_2 = graph_1 / 5.6
graph_3 = t3 + t4
graph_complete = tf.minimum(graph_2, graph_3)

 
# Let's execute
sess = tf.Session()
part1_res, part2_res, part3_res, total_res = sess.run([graph_1, graph_2, graph_3, graph_complete])
print ('Complete Result: ', total_res)
print ('Part 1 Result: ', part1_res)
print ('Part 2 Result: ', part2_res)
print ('Part 3 Result: ', part3_res)
sess.close()

Complete Result:  [11.25     15.446429]
Part 1 Result:  [63.  86.5]
Part 2 Result:  [11.25     15.446429]
Part 3 Result:  [21.15 16.18]


Let's do another!<br/>
It's fun! Isn't it?!

Build and execute this one!

![alt text](https://raw.githubusercontent.com/iArunava/TensorFlow-NoteBooks/master/assets/comp_graph_4.jpg)

In [10]:

# Build the graph
graph_1 = tf.multiply(
    tf.cast(tf.reduce_mean(tf.constant([[1.2,3.4],[7.5,8.6]])),dtype=tf.float32),
    tf.cast(tf.constant([[7,9],[8,6]]),dtype=tf.float32))


graph_2 = tf.reduce_sum(tf.multiply(tf.constant([[2.79,3.81,5.6],[7.3,5.67,8.9]]),tf.transpose(tf.constant([[2.6,18.1],[7.86,9.81],[9.36,10.11]]))))


graph_complete = tf.add(graph_1, graph_2)

# Execute 
sess = tf.Session()
part1_res, part2_res, total_res = sess.run([graph_1, graph_2, graph_complete])
print ('Complete Result: ', total_res)
print ('Part 1 Result: ', part1_res)
print ('Part 2 Result: ', part2_res)
sess.close()

Complete Result:  [[403.5733 413.9233]
 [408.7483 398.3983]]
Part 1 Result:  [[36.225002 46.575   ]
 [41.4      31.050001]]
Part 2 Result:  367.3483


And a final one, before we move on to the next part!

![alt text](https://raw.githubusercontent.com/iArunava/TensorFlow-NoteBooks/master/assets/comp_graph_5.jpg)

In [11]:
# Build the graph
graph_1 = tf.divide(
    tf.add(
        tf.constant(7.0),
        tf.reduce_sum(
            tf.multiply(
                tf.constant([[7.36,8.91,10.41],[5.31,9.38,7.99]]),
                tf.transpose(tf.constant([[7.99,10.36],[5.36,7.98],[8.91,5.67]]))
            )
        )),
    tf.constant(19.6))


graph_2 = tf.cast(tf.constant([[1,5.6,6.1,8],[0,0,7.98,9],[0,0,7.6,9],[0,0,0,8.98]]),dtype=tf.float32)

graph_complete = tf.divide(graph_1, graph_2)

# Execute 
sess = tf.Session()
part1_res, part2_res, total_res = sess.run([graph_1, graph_2, graph_complete])
print ('Complete Result: ', total_res)
print ('Part 1 Result: ', part1_res)
print ('Part 2 Result: ', part2_res)
sess.close()

Complete Result:  [[19.463488   3.475623   3.1907358  2.432936 ]
 [       inf        inf  2.4390335  2.1626098]
 [       inf        inf  2.5609853  2.1626098]
 [       inf        inf        inf  2.1674263]]
Part 1 Result:  19.463488
Part 2 Result:  [[1.   5.6  6.1  8.  ]
 [0.   0.   7.98 9.  ]
 [0.   0.   7.6  9.  ]
 [0.   0.   0.   8.98]]


# Linear Regression

Okay, now we will create a dummy dataset and perform linear regression on this dataset!


To get you in the habit of looking up for the documentation, I am not providing what some of the following functions does, Google them up!

In [0]:
# Create the dataset
X = np.linspace(-30.0, 300.0, 300)
Y = 2 * np.linspace(-30.0, 250.0, 300) + np.random.randn(*X.shape)

# Divide it into train and test
train_X = X[:250]
train_Y = Y[:250]

test_X = X[250:]
test_Y = Y[250:]

In [0]:
# Let's define the hyperparameters
learning_rate = 0.000005
n_epochs = 1000
interval = 50

In [0]:
# let's viz the first 10 datapoints of the dataset
plt.plot(train_X[:10], train_Y[:10], 'g')
plt.show()

** Question **<br/>
Why did I created a session to plot the graph?<br/>
[Ans]

In [0]:
# Let's define the placeholders

# Placeholders?
# The input to the model changes on iteration
# So we cannot have a constant in the input as we did before
# And thus we need placeholders which we can change on each 
# iteration of the training

x = tf.placeholder(tf.float32, name='x')
y = tf.placeholder(tf.float32, name='y')

In [0]:
# Let's define the linear regression model

# tf.Variable?
# We define the model parameters as tf.Variables
# as they get updated throghout the training.
# And variables denotes something which changes overtime.

W = tf.Variable(0.0, name='weight_1')
b = tf.Variable(0.0, name='bias_1')

pred_y = (W*x) + b

In [0]:
# Let's define the loss function
# We are going to use the mean squared loss
loss = tf.reduce_mean(tf.square(y - pred_y))

In [0]:
# Let's define the optimizer
# And specify the which value (i.e. loss) it has to minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(loss)

In [0]:
# So the graph is now built
# Now let's execute the graph using session
# i.e. lets train the model

# What it is to train a model?
# To update the paramters in the graph (i.e. tf.Variables)
# So that the loss is minimized

# Okay let's start!
with tf.Session() as sess:
  # We need to initialize the variables in our graph
  sess.run(tf.global_variables_initializer())
  
  for epoch in range(n_epochs):
    _, curr_loss = sess.run([optimizer, loss], feed_dict={x:train_X, y:train_Y})
    
    if epoch % interval == 0:
      print ('Loss after epoch', epoch, ' is ', curr_loss)
    
  print ('Now testing the model in the test set')
  final_preds, final_loss = sess.run([pred_y, loss], feed_dict={x:test_X, y:test_Y})
    
  print ('The final loss is: ', final_loss)
  
  # Plotting the final predictions against the true predictions
  plt.plot(test_X[:10], test_Y[:10], 'g', label='True Function')
  plt.plot(test_X[:10], final_preds[:10], 'r', label='Predicted Function')
  plt.legend()
  plt.show()

Okay, so we are doing good!<br/>

Now, let me just put everything here into one function so that you can tweak the hyperparameters easily!

Or better, do it yourself!

In [0]:
def linear_regression(learning_rate=0.000005, n_epochs=100, interval=50):
  # YOUR CODE HERE
  pass

In [0]:
# Okay! Now let's tweak!
linear_regression(learning_rate=0.000034, n_epochs=500)

In [0]:
linear_regression(learning_rate=0.0000006, n_epochs=1000)

## Drive the loss to a minimum.

In [0]:
# YOUR CODE HERE